### ISSUE TITLE
Any ideas on not being able to see the chat?

### ISSUE THREAD

**Issue by THREELabs** [baxsm/chatgpt-website#1]
Any ideas why I'm seeing issues?

http://dev.threeskate.com:5000  says {"message":"Working!"}

http://dev.threeskate.com:5000/chat  says Cannot get chat

**Comment by baxsm** [comment]
`/chat` is not an endpoint, or atleast not configured. The working POST endpoint is `/` https://github.com/baxsm/chatgpt-website/blob/ac2c349f56b309c29406f1655332d7207f2b54fa/server/server.js#L24

https://github.com/baxsm/chatgpt-website/blob/390d3a8062c8898065683a5a481535833dd388ab/client/script.js#L74
